// Municípios de Santa Catarina (IBGE, 295) com as duas divisões regionais
// usadas na tela de Resultados: mesorregião (IBGE, oficial) e associação de
// municípios (FECAM, 21 associações) — vínculo conferido município a
// município pela tabela "Municípios Catarinenses e Regiões" trazida pelo
// usuário em 21/09/2026. `chave` = nome sem acento, maiúsculo — é
// como o TSE grafa NM_MUNICIPIO, serve pra casar com os CSVs de votação.
// Fonte da malha: dados/mapas/sc-municipios.geojson (IBGE, qualidade mínima).
const MUNICIPIOS_SC_REGIOES = [
  { ibge:"4200051", nome:"Abdon Batista", chave:"ABDON BATISTA", meso:"Serrana", micro:"Curitibanos", assoc:"AMPLASC" },
  { ibge:"4200101", nome:"Abelardo Luz", chave:"ABELARDO LUZ", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4200200", nome:"Agrolândia", chave:"AGROLANDIA", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4200309", nome:"Agronômica", chave:"AGRONOMICA", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4200705", nome:"Alfredo Wagner", chave:"ALFREDO WAGNER", meso:"Grande Florianópolis", micro:"Tabuleiro", assoc:"GRANFPOLIS" },
  { ibge:"4200754", nome:"Alto Bela Vista", chave:"ALTO BELA VISTA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4200804", nome:"Anchieta", chave:"ANCHIETA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4200903", nome:"Angelina", chave:"ANGELINA", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4201000", nome:"Anita Garibaldi", chave:"ANITA GARIBALDI", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4201109", nome:"Anitápolis", chave:"ANITAPOLIS", meso:"Grande Florianópolis", micro:"Tabuleiro", assoc:"GRANFPOLIS" },
  { ibge:"4201208", nome:"Antônio Carlos", chave:"ANTONIO CARLOS", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4201257", nome:"Apiúna", chave:"APIUNA", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4201273", nome:"Arabutã", chave:"ARABUTA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4201307", nome:"Araquari", chave:"ARAQUARI", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMUNESC" },
  { ibge:"4201406", nome:"Araranguá", chave:"ARARANGUA", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4201505", nome:"Armazém", chave:"ARMAZEM", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4201604", nome:"Arroio Trinta", chave:"ARROIO TRINTA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4201653", nome:"Arvoredo", chave:"ARVOREDO", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMOSC" },
  { ibge:"4201703", nome:"Ascurra", chave:"ASCURRA", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4201802", nome:"Atalanta", chave:"ATALANTA", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4201901", nome:"Aurora", chave:"AURORA", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4201950", nome:"Balneário Arroio do Silva", chave:"BALNEARIO ARROIO DO SILVA", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4202057", nome:"Balneário Barra do Sul", chave:"BALNEARIO BARRA DO SUL", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMUNESC" },
  { ibge:"4202008", nome:"Balneário Camboriú", chave:"BALNEARIO CAMBORIU", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4202073", nome:"Balneário Gaivota", chave:"BALNEARIO GAIVOTA", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4212809", nome:"Balneário Piçarras", chave:"BALNEARIO PICARRAS", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4220000", nome:"Balneário Rincão", chave:"BALNEARIO RINCAO", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4202081", nome:"Bandeirante", chave:"BANDEIRANTE", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4202099", nome:"Barra Bonita", chave:"BARRA BONITA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4202107", nome:"Barra Velha", chave:"BARRA VELHA", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMVALI" },
  { ibge:"4202131", nome:"Bela Vista do Toldo", chave:"BELA VISTA DO TOLDO", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4202156", nome:"Belmonte", chave:"BELMONTE", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4202206", nome:"Benedito Novo", chave:"BENEDITO NOVO", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4202305", nome:"Biguaçu", chave:"BIGUACU", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4202404", nome:"Blumenau", chave:"BLUMENAU", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4202438", nome:"Bocaina do Sul", chave:"BOCAINA DO SUL", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4202503", nome:"Bom Jardim da Serra", chave:"BOM JARDIM DA SERRA", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4202537", nome:"Bom Jesus", chave:"BOM JESUS", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4202578", nome:"Bom Jesus do Oeste", chave:"BOM JESUS DO OESTE", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4202602", nome:"Bom Retiro", chave:"BOM RETIRO", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4202453", nome:"Bombinhas", chave:"BOMBINHAS", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4202701", nome:"Botuverá", chave:"BOTUVERA", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4202800", nome:"Braço do Norte", chave:"BRACO DO NORTE", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4202859", nome:"Braço do Trombudo", chave:"BRACO DO TROMBUDO", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4202875", nome:"Brunópolis", chave:"BRUNOPOLIS", meso:"Serrana", micro:"Curitibanos", assoc:"AMPLASC" },
  { ibge:"4202909", nome:"Brusque", chave:"BRUSQUE", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4203105", nome:"Caibi", chave:"CAIBI", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4203154", nome:"Calmon", chave:"CALMON", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4203204", nome:"Camboriú", chave:"CAMBORIU", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4203303", nome:"Campo Alegre", chave:"CAMPO ALEGRE", meso:"Norte Catarinense", micro:"São Bento do Sul", assoc:"AMUNESC" },
  { ibge:"4203402", nome:"Campo Belo do Sul", chave:"CAMPO BELO DO SUL", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4203501", nome:"Campo Erê", chave:"CAMPO ERE", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4203600", nome:"Campos Novos", chave:"CAMPOS NOVOS", meso:"Serrana", micro:"Curitibanos", assoc:"AMPLASC" },
  { ibge:"4203709", nome:"Canelinha", chave:"CANELINHA", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4203808", nome:"Canoinhas", chave:"CANOINHAS", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4203907", nome:"Capinzal", chave:"CAPINZAL", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4203956", nome:"Capivari de Baixo", chave:"CAPIVARI DE BAIXO", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4203253", nome:"Capão Alto", chave:"CAPAO ALTO", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4204004", nome:"Catanduvas", chave:"CATANDUVAS", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4204103", nome:"Caxambu do Sul", chave:"CAXAMBU DO SUL", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4203006", nome:"Caçador", chave:"CACADOR", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4204152", nome:"Celso Ramos", chave:"CELSO RAMOS", meso:"Serrana", micro:"Campos de Lages", assoc:"AMPLASC" },
  { ibge:"4204178", nome:"Cerro Negro", chave:"CERRO NEGRO", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4204194", nome:"Chapadão do Lageado", chave:"CHAPADAO DO LAGEADO", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4204202", nome:"Chapecó", chave:"CHAPECO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4204251", nome:"Cocal do Sul", chave:"COCAL DO SUL", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4204301", nome:"Concórdia", chave:"CONCORDIA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4204350", nome:"Cordilheira Alta", chave:"CORDILHEIRA ALTA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4204400", nome:"Coronel Freitas", chave:"CORONEL FREITAS", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4204459", nome:"Coronel Martins", chave:"CORONEL MARTINS", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMNOROESTE" },
  { ibge:"4204558", nome:"Correia Pinto", chave:"CORREIA PINTO", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4204509", nome:"Corupá", chave:"CORUPA", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMVALI" },
  { ibge:"4204608", nome:"Criciúma", chave:"CRICIUMA", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4204707", nome:"Cunha Porã", chave:"CUNHA PORA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4204756", nome:"Cunhataí", chave:"CUNHATAI", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4204806", nome:"Curitibanos", chave:"CURITIBANOS", meso:"Serrana", micro:"Curitibanos", assoc:"AMURC" },
  { ibge:"4204905", nome:"Descanso", chave:"DESCANSO", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4205001", nome:"Dionísio Cerqueira", chave:"DIONISIO CERQUEIRA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4205100", nome:"Dona Emma", chave:"DONA EMMA", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4205159", nome:"Doutor Pedrinho", chave:"DOUTOR PEDRINHO", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4205175", nome:"Entre Rios", chave:"ENTRE RIOS", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4205191", nome:"Ermo", chave:"ERMO", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4205209", nome:"Erval Velho", chave:"ERVAL VELHO", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4205308", nome:"Faxinal dos Guedes", chave:"FAXINAL DOS GUEDES", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4205357", nome:"Flor do Sertão", chave:"FLOR DO SERTAO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4205407", nome:"Florianópolis", chave:"FLORIANOPOLIS", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4205431", nome:"Formosa do Sul", chave:"FORMOSA DO SUL", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4205456", nome:"Forquilhinha", chave:"FORQUILHINHA", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4205506", nome:"Fraiburgo", chave:"FRAIBURGO", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4205555", nome:"Frei Rogério", chave:"FREI ROGERIO", meso:"Serrana", micro:"Curitibanos", assoc:"AMURC" },
  { ibge:"4205605", nome:"Galvão", chave:"GALVAO", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMNOROESTE" },
  { ibge:"4205704", nome:"Garopaba", chave:"GAROPABA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"GRANFPOLIS" },
  { ibge:"4205803", nome:"Garuva", chave:"GARUVA", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMUNESC" },
  { ibge:"4205902", nome:"Gaspar", chave:"GASPAR", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4206009", nome:"Governador Celso Ramos", chave:"GOVERNADOR CELSO RAMOS", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4206207", nome:"Gravatal", chave:"GRAVATAL", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4206108", nome:"Grão-Pará", chave:"GRAO-PARA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4206306", nome:"Guabiruba", chave:"GUABIRUBA", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4206405", nome:"Guaraciaba", chave:"GUARACIABA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4206504", nome:"Guaramirim", chave:"GUARAMIRIM", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMVALI" },
  { ibge:"4206603", nome:"Guarujá do Sul", chave:"GUARUJA DO SUL", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4206652", nome:"Guatambú", chave:"GUATAMBU", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4206702", nome:"Herval d'Oeste", chave:"HERVAL D OESTE", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4206751", nome:"Ibiam", chave:"IBIAM", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4206801", nome:"Ibicaré", chave:"IBICARE", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4206900", nome:"Ibirama", chave:"IBIRAMA", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4207106", nome:"Ilhota", chave:"ILHOTA", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4207205", nome:"Imaruí", chave:"IMARUI", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4207304", nome:"Imbituba", chave:"IMBITUBA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4207403", nome:"Imbuia", chave:"IMBUIA", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4207502", nome:"Indaial", chave:"INDAIAL", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4207577", nome:"Iomerê", chave:"IOMERE", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4207601", nome:"Ipira", chave:"IPIRA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4207650", nome:"Iporã do Oeste", chave:"IPORA DO OESTE", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4207684", nome:"Ipuaçu", chave:"IPUACU", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4207700", nome:"Ipumirim", chave:"IPUMIRIM", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4207759", nome:"Iraceminha", chave:"IRACEMINHA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4207809", nome:"Irani", chave:"IRANI", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4207858", nome:"Irati", chave:"IRATI", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMNOROESTE" },
  { ibge:"4207908", nome:"Irineópolis", chave:"IRINEOPOLIS", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4208104", nome:"Itaiópolis", chave:"ITAIOPOLIS", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4208203", nome:"Itajaí", chave:"ITAJAI", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4208302", nome:"Itapema", chave:"ITAPEMA", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4208401", nome:"Itapiranga", chave:"ITAPIRANGA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4208450", nome:"Itapoá", chave:"ITAPOA", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMUNESC" },
  { ibge:"4208500", nome:"Ituporanga", chave:"ITUPORANGA", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4208005", nome:"Itá", chave:"ITA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4207007", nome:"Içara", chave:"ICARA", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4208609", nome:"Jaborá", chave:"JABORA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMAUC" },
  { ibge:"4208708", nome:"Jacinto Machado", chave:"JACINTO MACHADO", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4208807", nome:"Jaguaruna", chave:"JAGUARUNA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4208906", nome:"Jaraguá do Sul", chave:"JARAGUA DO SUL", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMVALI" },
  { ibge:"4208955", nome:"Jardinópolis", chave:"JARDINOPOLIS", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4209003", nome:"Joaçaba", chave:"JOACABA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4209102", nome:"Joinville", chave:"JOINVILLE", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMUNESC" },
  { ibge:"4209151", nome:"José Boiteux", chave:"JOSE BOITEUX", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4209177", nome:"Jupiá", chave:"JUPIA", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMNOROESTE" },
  { ibge:"4209201", nome:"Lacerdópolis", chave:"LACERDOPOLIS", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4209300", nome:"Lages", chave:"LAGES", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4209409", nome:"Laguna", chave:"LAGUNA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4209458", nome:"Lajeado Grande", chave:"LAJEADO GRANDE", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4209508", nome:"Laurentino", chave:"LAURENTINO", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4209607", nome:"Lauro Müller", chave:"LAURO MULLER", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4209706", nome:"Lebon Régis", chave:"LEBON REGIS", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4209805", nome:"Leoberto Leal", chave:"LEOBERTO LEAL", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4209854", nome:"Lindóia do Sul", chave:"LINDOIA DO SUL", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4209904", nome:"Lontras", chave:"LONTRAS", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4210001", nome:"Luiz Alves", chave:"LUIZ ALVES", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMFRI" },
  { ibge:"4210035", nome:"Luzerna", chave:"LUZERNA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4210050", nome:"Macieira", chave:"MACIEIRA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4210100", nome:"Mafra", chave:"MAFRA", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4210209", nome:"Major Gercino", chave:"MAJOR GERCINO", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4210308", nome:"Major Vieira", chave:"MAJOR VIEIRA", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4210407", nome:"Maracajá", chave:"MARACAJA", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4210506", nome:"Maravilha", chave:"MARAVILHA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4210555", nome:"Marema", chave:"MAREMA", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4210605", nome:"Massaranduba", chave:"MASSARANDUBA", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMVALI" },
  { ibge:"4210704", nome:"Matos Costa", chave:"MATOS COSTA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4210803", nome:"Meleiro", chave:"MELEIRO", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4210852", nome:"Mirim Doce", chave:"MIRIM DOCE", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4210902", nome:"Modelo", chave:"MODELO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4211009", nome:"Mondaí", chave:"MONDAI", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4211058", nome:"Monte Carlo", chave:"MONTE CARLO", meso:"Serrana", micro:"Curitibanos", assoc:"AMPLASC" },
  { ibge:"4211108", nome:"Monte Castelo", chave:"MONTE CASTELO", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4211256", nome:"Morro Grande", chave:"MORRO GRANDE", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4211207", nome:"Morro da Fumaça", chave:"MORRO DA FUMACA", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4211306", nome:"Navegantes", chave:"NAVEGANTES", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4211405", nome:"Nova Erechim", chave:"NOVA ERECHIM", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4211454", nome:"Nova Itaberaba", chave:"NOVA ITABERABA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4211504", nome:"Nova Trento", chave:"NOVA TRENTO", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4211603", nome:"Nova Veneza", chave:"NOVA VENEZA", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4211652", nome:"Novo Horizonte", chave:"NOVO HORIZONTE", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMNOROESTE" },
  { ibge:"4211702", nome:"Orleans", chave:"ORLEANS", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMREC" },
  { ibge:"4211751", nome:"Otacílio Costa", chave:"OTACILIO COSTA", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4211801", nome:"Ouro", chave:"OURO", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4211850", nome:"Ouro Verde", chave:"OURO VERDE", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4211876", nome:"Paial", chave:"PAIAL", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMOSC" },
  { ibge:"4211892", nome:"Painel", chave:"PAINEL", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4211900", nome:"Palhoça", chave:"PALHOCA", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4212007", nome:"Palma Sola", chave:"PALMA SOLA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4212056", nome:"Palmeira", chave:"PALMEIRA", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4212106", nome:"Palmitos", chave:"PALMITOS", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4212205", nome:"Papanduva", chave:"PAPANDUVA", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4212239", nome:"Paraíso", chave:"PARAISO", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4212254", nome:"Passo de Torres", chave:"PASSO DE TORRES", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4212270", nome:"Passos Maia", chave:"PASSOS MAIA", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4212304", nome:"Paulo Lopes", chave:"PAULO LOPES", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4212403", nome:"Pedras Grandes", chave:"PEDRAS GRANDES", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4212502", nome:"Penha", chave:"PENHA", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4212601", nome:"Peritiba", chave:"PERITIBA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4212650", nome:"Pescaria Brava", chave:"PESCARIA BRAVA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4212700", nome:"Petrolândia", chave:"PETROLANDIA", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4212908", nome:"Pinhalzinho", chave:"PINHALZINHO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4213005", nome:"Pinheiro Preto", chave:"PINHEIRO PRETO", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4213104", nome:"Piratuba", chave:"PIRATUBA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4213153", nome:"Planalto Alegre", chave:"PLANALTO ALEGRE", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4213203", nome:"Pomerode", chave:"POMERODE", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4213302", nome:"Ponte Alta", chave:"PONTE ALTA", meso:"Serrana", micro:"Curitibanos", assoc:"AMURES" },
  { ibge:"4213351", nome:"Ponte Alta do Norte", chave:"PONTE ALTA DO NORTE", meso:"Serrana", micro:"Curitibanos", assoc:"AMURC" },
  { ibge:"4213401", nome:"Ponte Serrada", chave:"PONTE SERRADA", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4213500", nome:"Porto Belo", chave:"PORTO BELO", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMFRI" },
  { ibge:"4213609", nome:"Porto União", chave:"PORTO UNIAO", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4213708", nome:"Pouso Redondo", chave:"POUSO REDONDO", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4213807", nome:"Praia Grande", chave:"PRAIA GRANDE", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4213906", nome:"Presidente Castello Branco", chave:"PRESIDENTE CASTELLO BRANCO", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4214003", nome:"Presidente Getúlio", chave:"PRESIDENTE GETULIO", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4214102", nome:"Presidente Nereu", chave:"PRESIDENTE NEREU", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4214151", nome:"Princesa", chave:"PRINCESA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4214201", nome:"Quilombo", chave:"QUILOMBO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMNOROESTE" },
  { ibge:"4214300", nome:"Rancho Queimado", chave:"RANCHO QUEIMADO", meso:"Grande Florianópolis", micro:"Tabuleiro", assoc:"GRANFPOLIS" },
  { ibge:"4214904", nome:"Rio Fortuna", chave:"RIO FORTUNA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4215000", nome:"Rio Negrinho", chave:"RIO NEGRINHO", meso:"Norte Catarinense", micro:"São Bento do Sul", assoc:"AMUNESC" },
  { ibge:"4215059", nome:"Rio Rufino", chave:"RIO RUFINO", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4214409", nome:"Rio das Antas", chave:"RIO DAS ANTAS", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4214508", nome:"Rio do Campo", chave:"RIO DO CAMPO", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4214607", nome:"Rio do Oeste", chave:"RIO DO OESTE", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4214805", nome:"Rio do Sul", chave:"RIO DO SUL", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4214706", nome:"Rio dos Cedros", chave:"RIO DOS CEDROS", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4215075", nome:"Riqueza", chave:"RIQUEZA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMERIOS" },
  { ibge:"4215109", nome:"Rodeio", chave:"RODEIO", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4215208", nome:"Romelândia", chave:"ROMELANDIA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMERIOS" },
  { ibge:"4215307", nome:"Salete", chave:"SALETE", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4215356", nome:"Saltinho", chave:"SALTINHO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4215406", nome:"Salto Veloso", chave:"SALTO VELOSO", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4215455", nome:"Sangão", chave:"SANGAO", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4215505", nome:"Santa Cecília", chave:"SANTA CECILIA", meso:"Serrana", micro:"Curitibanos", assoc:"AMURC" },
  { ibge:"4215554", nome:"Santa Helena", chave:"SANTA HELENA", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4215604", nome:"Santa Rosa de Lima", chave:"SANTA ROSA DE LIMA", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4215653", nome:"Santa Rosa do Sul", chave:"SANTA ROSA DO SUL", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4215679", nome:"Santa Terezinha", chave:"SANTA TEREZINHA", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMAVI" },
  { ibge:"4215687", nome:"Santa Terezinha do Progresso", chave:"SANTA TEREZINHA DO PROGRESSO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4215695", nome:"Santiago do Sul", chave:"SANTIAGO DO SUL", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4215703", nome:"Santo Amaro da Imperatriz", chave:"SANTO AMARO DA IMPERATRIZ", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4217303", nome:"Saudades", chave:"SAUDADES", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4217402", nome:"Schroeder", chave:"SCHROEDER", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMVALI" },
  { ibge:"4217501", nome:"Seara", chave:"SEARA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4217550", nome:"Serra Alta", chave:"SERRA ALTA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4217600", nome:"Siderópolis", chave:"SIDEROPOLIS", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4217709", nome:"Sombrio", chave:"SOMBRIO", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4217758", nome:"Sul Brasil", chave:"SUL BRASIL", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4215802", nome:"São Bento do Sul", chave:"SAO BENTO DO SUL", meso:"Norte Catarinense", micro:"São Bento do Sul", assoc:"AMUNESC" },
  { ibge:"4215752", nome:"São Bernardino", chave:"SAO BERNARDINO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMNOROESTE" },
  { ibge:"4215901", nome:"São Bonifácio", chave:"SAO BONIFACIO", meso:"Grande Florianópolis", micro:"Tabuleiro", assoc:"GRANFPOLIS" },
  { ibge:"4216008", nome:"São Carlos", chave:"SAO CARLOS", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4216057", nome:"São Cristóvão do Sul", chave:"SAO CRISTOVAO DO SUL", meso:"Serrana", micro:"Curitibanos", assoc:"AMURC" },
  { ibge:"4216107", nome:"São Domingos", chave:"SAO DOMINGOS", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4216206", nome:"São Francisco do Sul", chave:"SAO FRANCISCO DO SUL", meso:"Norte Catarinense", micro:"Joinville", assoc:"AMUNESC" },
  { ibge:"4216503", nome:"São Joaquim", chave:"SAO JOAQUIM", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4216602", nome:"São José", chave:"SAO JOSE", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4216701", nome:"São José do Cedro", chave:"SAO JOSE DO CEDRO", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4216800", nome:"São José do Cerrito", chave:"SAO JOSE DO CERRITO", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4216305", nome:"São João Batista", chave:"SAO JOAO BATISTA", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4216354", nome:"São João do Itaperiú", chave:"SAO JOAO DO ITAPERIU", meso:"Vale do Itajaí", micro:"Itajaí", assoc:"AMVALI" },
  { ibge:"4216255", nome:"São João do Oeste", chave:"SAO JOAO DO OESTE", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4216404", nome:"São João do Sul", chave:"SAO JOAO DO SUL", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4216909", nome:"São Lourenço do Oeste", chave:"SAO LOURENCO DO OESTE", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMNOROESTE" },
  { ibge:"4217006", nome:"São Ludgero", chave:"SAO LUDGERO", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4217105", nome:"São Martinho", chave:"SAO MARTINHO", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4217154", nome:"São Miguel da Boa Vista", chave:"SAO MIGUEL DA BOA VISTA", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4217204", nome:"São Miguel do Oeste", chave:"SAO MIGUEL DO OESTE", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4217253", nome:"São Pedro de Alcântara", chave:"SAO PEDRO DE ALCANTARA", meso:"Grande Florianópolis", micro:"Florianópolis", assoc:"GRANFPOLIS" },
  { ibge:"4217808", nome:"Taió", chave:"TAIO", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4217907", nome:"Tangará", chave:"TANGARA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4217956", nome:"Tigrinhos", chave:"TIGRINHOS", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMERIOS" },
  { ibge:"4218004", nome:"Tijucas", chave:"TIJUCAS", meso:"Grande Florianópolis", micro:"Tijucas", assoc:"GRANFPOLIS" },
  { ibge:"4218103", nome:"Timbé do Sul", chave:"TIMBE DO SUL", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4218202", nome:"Timbó", chave:"TIMBO", meso:"Vale do Itajaí", micro:"Blumenau", assoc:"AMVE" },
  { ibge:"4218251", nome:"Timbó Grande", chave:"TIMBO GRANDE", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMARP" },
  { ibge:"4218350", nome:"Treviso", chave:"TREVISO", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4218509", nome:"Treze Tílias", chave:"TREZE TILIAS", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4218400", nome:"Treze de Maio", chave:"TREZE DE MAIO", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4218608", nome:"Trombudo Central", chave:"TROMBUDO CENTRAL", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4218301", nome:"Três Barras", chave:"TRES BARRAS", meso:"Norte Catarinense", micro:"Canoinhas", assoc:"AMPLANORTE" },
  { ibge:"4218707", nome:"Tubarão", chave:"TUBARAO", meso:"Sul Catarinense", micro:"Tubarão", assoc:"AMUREL" },
  { ibge:"4218756", nome:"Tunápolis", chave:"TUNAPOLIS", meso:"Oeste Catarinense", micro:"São Miguel do Oeste", assoc:"AMEOSC" },
  { ibge:"4218806", nome:"Turvo", chave:"TURVO", meso:"Sul Catarinense", micro:"Araranguá", assoc:"AMESC" },
  { ibge:"4218855", nome:"União do Oeste", chave:"UNIAO DO OESTE", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4218905", nome:"Urubici", chave:"URUBICI", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4218954", nome:"Urupema", chave:"URUPEMA", meso:"Serrana", micro:"Campos de Lages", assoc:"AMURES" },
  { ibge:"4219002", nome:"Urussanga", chave:"URUSSANGA", meso:"Sul Catarinense", micro:"Criciúma", assoc:"AMREC" },
  { ibge:"4219150", nome:"Vargem", chave:"VARGEM", meso:"Serrana", micro:"Curitibanos", assoc:"AMPLASC" },
  { ibge:"4219176", nome:"Vargem Bonita", chave:"VARGEM BONITA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4219101", nome:"Vargeão", chave:"VARGEAO", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4219200", nome:"Vidal Ramos", chave:"VIDAL RAMOS", meso:"Vale do Itajaí", micro:"Ituporanga", assoc:"AMAVI" },
  { ibge:"4219309", nome:"Videira", chave:"VIDEIRA", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMARP" },
  { ibge:"4219358", nome:"Vitor Meireles", chave:"VITOR MEIRELES", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4219408", nome:"Witmarsum", chave:"WITMARSUM", meso:"Vale do Itajaí", micro:"Rio do Sul", assoc:"AMAVI" },
  { ibge:"4219507", nome:"Xanxerê", chave:"XANXERE", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4219606", nome:"Xavantina", chave:"XAVANTINA", meso:"Oeste Catarinense", micro:"Concórdia", assoc:"AMAUC" },
  { ibge:"4219705", nome:"Xaxim", chave:"XAXIM", meso:"Oeste Catarinense", micro:"Xanxerê", assoc:"AMAI" },
  { ibge:"4219853", nome:"Zortéa", chave:"ZORTEA", meso:"Serrana", micro:"Curitibanos", assoc:"AMPLASC" },
  { ibge:"4200408", nome:"Água Doce", chave:"AGUA DOCE", meso:"Oeste Catarinense", micro:"Joaçaba", assoc:"AMMOC" },
  { ibge:"4200556", nome:"Águas Frias", chave:"AGUAS FRIAS", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" },
  { ibge:"4200606", nome:"Águas Mornas", chave:"AGUAS MORNAS", meso:"Grande Florianópolis", micro:"Tabuleiro", assoc:"GRANFPOLIS" },
  { ibge:"4200507", nome:"Águas de Chapecó", chave:"AGUAS DE CHAPECO", meso:"Oeste Catarinense", micro:"Chapecó", assoc:"AMOSC" }
];
const ASSOCIACOES_SC = ["AMAI", "AMARP", "AMAUC", "AMAVI", "AMEOSC", "AMERIOS", "AMESC", "AMFRI", "AMMOC", "AMOSC", "AMPLANORTE", "AMPLASC", "AMREC", "AMUNESC", "AMURC", "AMUREL", "AMURES", "AMVALI", "AMVE", "GRANFPOLIS", "AMNOROESTE"];
